# This .travis.yml is modified from the sample at
# https://docs.haskellstack.org/en/stable/GUIDE/#travis-with-caching

# Allow sudo to enable 'mount'
sudo: true

# Do not choose a language; we provide our own build tools.
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/drives

# The different configurations we want to test. We have BUILD=cabal which uses
# cabal-install, and BUILD=stack which uses Stack. More documentation on each
# of those below.
#
# We set the compiler values here to tell Travis to use a different
# cache file per set of arguments.
#
# If you need to have different apt packages for each combination in the
# matrix, you can use a line such as:
#     addons: {apt: {packages: [libfcgi-dev,libgmp-dev]}}
#
# fast_finish: build successful when every builds not in allow_failure are finished
# i.e. not waiting any of the allow_failure to finish
matrix:
  include:
  - env: BUILD=stack ARGS="--resolver lts-10" OPTS="-Wall -Wincomplete-record-updates -Wnoncanonical-monad-instances -Wnoncanonical-monadfail-instances -fno-warn-unused-do-bind -Werror"
    compiler: ": #stack 8.2.2"
    addons: {apt: {packages: [ghc-8.2.2], sources: [hvr-ghc]}}

  fast_finish: true

before_install:
# Create drives for ~/.stack and .stack-work, or unpack them if they exist
# in cache (we need to pack with tar --sparse because otherwise the cache
# would take 40GB)
- mkdir -p $HOME/drives
- pushd $HOME/drives
- |
  if [ -f stack.img.tar ]; then
    tar -xvf stack.img.tar stack.img
    rm stack.img.tar
  else
    truncate -s 20G stack.img
    mkfs -F -t ext4 stack.img
  fi
- |
  if [ -f stack-work.img.tar ]; then
    tar -xvf stack-work.img.tar stack-work.img
    rm stack-work.img.tar
  else
    truncate -s 20G stack-work.img
    mkfs -F -t ext4 stack-work.img
  fi
- popd
# Mount ~/.stack
- rm -rf $HOME/.stack && mkdir $HOME/.stack
- sudo mount $HOME/drives/stack.img $HOME/.stack
- sudo chown -R $USER $HOME/.stack
# Mount .stack-work
- rm -rf .stack-work && mkdir .stack-work
- sudo mount $HOME/drives/stack-work.img .stack-work
- sudo chown -R $USER .stack-work
# Using compiler above sets CC to an invalid value, so unset it
- unset CC
- export PATH=/opt/happy/1.19.5/bin/:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.local/bin:$HOME/.cabal/bin:$PATH
# Download and unpack the stack executable
- |
  if [[ $BUILD == "stack" ]]; then
    mkdir -p ~/.local/bin
    if [ `uname` = "Darwin" ]
    then
      curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
    else
      curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    fi
  fi

install:
- echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
- if [ -f configure.ac ]; then autoreconf -i; fi
- |
  case "$BUILD" in
    stack)
      ulimit -n 4096
      stack config set system-ghc --global true
      stack --no-terminal --install-ghc $ARGS build --only-dependencies --fast --flag 'pandoc:embed_data_files' --flag 'aeson:fast' --jobs 2
      ;;
    cabal)
      cabal --version
      travis_retry cabal update
      cabal install --disable-optimization --only-dependencies --flags="$FLAGS" --enable-tests --force-reinstalls --reorder-goals --max-backjumps=-1 $CABALARGS
      ;;
  esac

script:
- |
  case "$BUILD" in
    stack)
      ulimit -n 4096
      stack config set system-ghc --global true
      stack --no-terminal $ARGS test --fast --flag 'aeson:fast' --flag pandoc:embed_data_files --haddock --no-haddock-deps --ghc-options="$OPTS"
      ;;
    cabal)
      cabal sdist --output-directory=sourcedist && \
      cd sourcedist && \
      cabal configure --disable-optimization --enable-tests -v2 --flags="$FLAGS" --ghc-options="$OPTS" $CABALARGS && \
      cabal build -v2 -j2 && \
      cabal test
      ;;
  esac

before_cache:
- sudo umount .stack-work
- sudo umount $HOME/.stack
- pushd $HOME/drives
- echo "actual size taken by cached .img files (drives)"
- ls -lahts *.img
- tar -cSvf stack.img.tar stack.img
- tar -cSvf stack-work.img.tar stack-work.img
- rm *.img
- popd
